require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetailersController do

  # This should return the minimal set of attributes required to create a valid
  # Retailer. As you add validations to Retailer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "retailer_id" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetailersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all retailers as @retailers" do
      retailer = Retailer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:retailers).should eq([retailer])
    end
  end

  describe "GET show" do
    it "assigns the requested retailer as @retailer" do
      retailer = Retailer.create! valid_attributes
      get :show, {:id => retailer.to_param}, valid_session
      assigns(:retailer).should eq(retailer)
    end
  end

  describe "GET new" do
    it "assigns a new retailer as @retailer" do
      get :new, {}, valid_session
      assigns(:retailer).should be_a_new(Retailer)
    end
  end

  describe "GET edit" do
    it "assigns the requested retailer as @retailer" do
      retailer = Retailer.create! valid_attributes
      get :edit, {:id => retailer.to_param}, valid_session
      assigns(:retailer).should eq(retailer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Retailer" do
        expect {
          post :create, {:retailer => valid_attributes}, valid_session
        }.to change(Retailer, :count).by(1)
      end

      it "assigns a newly created retailer as @retailer" do
        post :create, {:retailer => valid_attributes}, valid_session
        assigns(:retailer).should be_a(Retailer)
        assigns(:retailer).should be_persisted
      end

      it "redirects to the created retailer" do
        post :create, {:retailer => valid_attributes}, valid_session
        response.should redirect_to(Retailer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved retailer as @retailer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retailer.any_instance.stub(:save).and_return(false)
        post :create, {:retailer => { "retailer_id" => "invalid value" }}, valid_session
        assigns(:retailer).should be_a_new(Retailer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retailer.any_instance.stub(:save).and_return(false)
        post :create, {:retailer => { "retailer_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested retailer" do
        retailer = Retailer.create! valid_attributes
        # Assuming there are no other retailers in the database, this
        # specifies that the Retailer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Retailer.any_instance.should_receive(:update_attributes).with({ "retailer_id" => "MyString" })
        put :update, {:id => retailer.to_param, :retailer => { "retailer_id" => "MyString" }}, valid_session
      end

      it "assigns the requested retailer as @retailer" do
        retailer = Retailer.create! valid_attributes
        put :update, {:id => retailer.to_param, :retailer => valid_attributes}, valid_session
        assigns(:retailer).should eq(retailer)
      end

      it "redirects to the retailer" do
        retailer = Retailer.create! valid_attributes
        put :update, {:id => retailer.to_param, :retailer => valid_attributes}, valid_session
        response.should redirect_to(retailer)
      end
    end

    describe "with invalid params" do
      it "assigns the retailer as @retailer" do
        retailer = Retailer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retailer.any_instance.stub(:save).and_return(false)
        put :update, {:id => retailer.to_param, :retailer => { "retailer_id" => "invalid value" }}, valid_session
        assigns(:retailer).should eq(retailer)
      end

      it "re-renders the 'edit' template" do
        retailer = Retailer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retailer.any_instance.stub(:save).and_return(false)
        put :update, {:id => retailer.to_param, :retailer => { "retailer_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested retailer" do
      retailer = Retailer.create! valid_attributes
      expect {
        delete :destroy, {:id => retailer.to_param}, valid_session
      }.to change(Retailer, :count).by(-1)
    end

    it "redirects to the retailers list" do
      retailer = Retailer.create! valid_attributes
      delete :destroy, {:id => retailer.to_param}, valid_session
      response.should redirect_to(retailers_url)
    end
  end

end
